app.py
from flask import Flask
from routes import pages

def create_app():
  app = Flask(__name__)
  app.register_blueprint(pages)

  return app

routes.py
from flask import Flask, render_template, request, redirect, url_for, Blueprint
from collections import defaultdict
import datetime

# app = Flask(__name__)

pages = Blueprint("habits", __name__, template_folder="templates", static_folder="static")

habits = ["Test habit"]
completions = defaultdict(list)


@pages.context_processor
def add_calc_date_range():
  def date_range(start: datetime.date):
    dates = [start + datetime.timedelta(days=diff) for diff in range(-3,4)]
    return dates
  
  return {"date_range": date_range}

@pages.route("/")
def index():
  date_str = request.args.get('date')

  if date_str:
    selected_date = datetime.date.fromisoformat(date_str)
  else:
    selected_date = datetime.date.today()

  return render_template("index.html", 
    habits=habits,
    selected_date=selected_date,
    title="Home",
    completions=completions[selected_date])

@pages.route("/add", methods=["GET","POST"])
def add_habit():
  
  if request.method == "POST":
    habits.append(request.form.get("habit"))
    
  return render_template("add_habit.html",
  selected_date=datetime.date.today(),
  title="Add Habit")

@pages.route("/complete", methods=["POST"])
def complete():
  date_string = request.form.get("date")
  date = datetime.date.fromisoformat(date_string)
  habit = request.form.get('habitName')
  completions[date].append(habit)
  
  return redirect(url_for(".index", date=date_string,habits=habit))

templates/add_habit.html
{% extends "layout.html" %}

{% block main_content %}
  <form class="form" method="POST">
    <textarea class="form__input"name="habit" id="habit" rows="3" placeholder="Add a new daily habit"></textarea>
    <button class="form__button" type="submit">Add</button>


  </form>

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_content %}
    <section class="habit-list">
    {% for habit in habits %}
        {% set completed = habit in completions %}
        {% if completed %}
        <div class="habit completed">
          <p class="habit__name">
            {{ habit }}
          </p>
          <svg class="habit__icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd"
              d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
              clip-rule="evenodd" />
          </svg>
        </div>
        {% else %}
        <div class="habit">
          <form method="POST" class="habit__form" action="{{url_for('habits.complete')}}">
            <input type="hidden" name="habitName" value="{{ habit}}">
            <input type="hidden" name="date" value="{{selected_date}}">
            <button type="submit" class="habit__btn">
              {{ habit }}
            </button>
          </form>
        </div>
        {% endif %}
    {% endfor %}
    </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Habit Tracker -{{ title }}</title>
  {% block head_content %}{% endblock %}
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
</head>

<body>
  <header class="header">
    <h1 class="header__logo">
      <a href="{{ url_for('habits.index') }}" class="header__link">Habits</a>
    </h1>
    {% if "add" not in request.endpoint %}
    <a href="{{ url_for('habits.add_habit') }}" class="header__link">+ Add new</a>
    {% endif %}

  </header>

  <main class="main">

    <section class="dates">
      {% for date in date_range(selected_date) %}
      <a href="{{ url_for('habits.index', date=date) }}"
        class="dates__link {{ 'dates__link--current' if loop.index == 4 else ''}}">
        <time class="date" datetime="{{ date }}">
          <span>{{ date.strftime("%a") }}</span>
          <span>{{ date.strftime("%d") }}</span>
        </time>
      </a>
      {% endfor %}
    </section>
    
    {% block main_content %}
    {% endblock %}
  </main>


</body>

</html>